package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// HTTP Metrics
	HttpRequestsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "marketbridge_http_requests_total",
			Help: "Total number of HTTP requests",
		},
		[]string{"method", "endpoint", "status"},
	)

	HttpRequestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "marketbridge_http_request_duration_seconds",
			Help:    "HTTP request duration in seconds",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"method", "endpoint"},
	)

	// Collector Metrics
	CollectorTicksReceived = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "marketbridge_collector_ticks_total",
			Help: "Total ticks received by collectors",
		},
		[]string{"collector_name", "symbol"},
	)

	CollectorBarsGenerated = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "marketbridge_collector_bars_total",
			Help: "Total bars generated by collectors",
		},
		[]string{"collector_name", "timeframe"},
	)

	CollectorErrors = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "marketbridge_collector_errors_total",
			Help: "Total collector errors",
		},
		[]string{"collector_name", "error_type"},
	)

	ActiveCollectors = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "marketbridge_active_collectors",
			Help: "Number of active collectors",
		},
	)

	// WebSocket Metrics
	WebSocketConnections = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "marketbridge_websocket_connections",
			Help: "Number of active WebSocket connections",
		},
	)

	WebSocketMessagesTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "marketbridge_websocket_messages_total",
			Help: "Total WebSocket messages sent",
		},
		[]string{"message_type"},
	)

	// Database Metrics
	DatabaseQueriesTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "marketbridge_database_queries_total",
			Help: "Total database queries executed",
		},
		[]string{"operation", "table"},
	)

	DatabaseQueryDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "marketbridge_database_query_duration_seconds",
			Help:    "Database query duration in seconds",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"operation", "table"},
	)

	DatabaseErrors = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "marketbridge_database_errors_total",
			Help: "Total database errors",
		},
		[]string{"operation", "error_type"},
	)

	// Data Quality Metrics
	DataCompletenessPercent = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "marketbridge_data_completeness_percent",
			Help: "Data completeness percentage by symbol",
		},
		[]string{"symbol"},
	)

	DataGapsDetected = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "marketbridge_data_gaps_total",
			Help: "Total data gaps detected",
		},
		[]string{"symbol", "timeframe"},
	)
)

// RecordHTTPRequest records an HTTP request
func RecordHTTPRequest(method, endpoint, status string, duration float64) {
	HttpRequestsTotal.WithLabelValues(method, endpoint, status).Inc()
	HttpRequestDuration.WithLabelValues(method, endpoint).Observe(duration)
}

// RecordTick records a tick received by a collector
func RecordTick(collectorName, symbol string) {
	CollectorTicksReceived.WithLabelValues(collectorName, symbol).Inc()
}

// RecordBar records a bar generated by a collector
func RecordBar(collectorName, timeframe string) {
	CollectorBarsGenerated.WithLabelValues(collectorName, timeframe).Inc()
}

// RecordCollectorError records a collector error
func RecordCollectorError(collectorName, errorType string) {
	CollectorErrors.WithLabelValues(collectorName, errorType).Inc()
}

// SetActiveCollectors sets the number of active collectors
func SetActiveCollectors(count int) {
	ActiveCollectors.Set(float64(count))
}

// IncrementWebSocketConnections increments WebSocket connection count
func IncrementWebSocketConnections() {
	WebSocketConnections.Inc()
}

// DecrementWebSocketConnections decrements WebSocket connection count
func DecrementWebSocketConnections() {
	WebSocketConnections.Dec()
}

// RecordWebSocketMessage records a WebSocket message
func RecordWebSocketMessage(messageType string) {
	WebSocketMessagesTotal.WithLabelValues(messageType).Inc()
}

// RecordDatabaseQuery records a database query
func RecordDatabaseQuery(operation, table string, duration float64) {
	DatabaseQueriesTotal.WithLabelValues(operation, table).Inc()
	DatabaseQueryDuration.WithLabelValues(operation, table).Observe(duration)
}

// RecordDatabaseError records a database error
func RecordDatabaseError(operation, errorType string) {
	DatabaseErrors.WithLabelValues(operation, errorType).Inc()
}

// SetDataCompleteness sets data completeness percentage for a symbol
func SetDataCompleteness(symbol string, percent float64) {
	DataCompletenessPercent.WithLabelValues(symbol).Set(percent)
}

// RecordDataGap records a data gap
func RecordDataGap(symbol, timeframe string) {
	DataGapsDetected.WithLabelValues(symbol, timeframe).Inc()
}
